import type { MinerAsset } from '../domain/types';

/** Small illustrative sample — clearly labeled demo, not operating inventory. */
export const DEMO_FLEET: MinerAsset[] = [
  {
    id: 'demo-s21-001',
    model: 'Antminer S21',
    serialNumber: 'DEMO-S21-001',
    quantity: 1,
    nominalHashrateTh: 200,
    wattage: 3500,
    acquisitionDate: '2025-06-01',
    acquisitionCostUsd: 4500,
    hostingProvider: 'Demo Host',
    facility: 'Demo Facility A',
    electricityRatePerKwh: 0.045,
    monthlyHostingFeeUsd: 0,
    pool: 'Braiins Pool',
    braiinsWorkerName: 'forge.demo1',
    status: 'active',
    enabled: true,
    warrantyExpiration: '2027-06-01',
    notes: 'Demo asset — not real inventory.',
    createdAt: '2025-06-01T00:00:00.000Z',
    updatedAt: '2025-06-01T00:00:00.000Z',
  },
  {
    id: 'demo-s21pro-001',
    model: 'Antminer S21 Pro',
    serialNumber: 'DEMO-S21P-001',
    quantity: 1,
    nominalHashrateTh: 234,
    wattage: 3510,
    acquisitionDate: '2025-08-15',
    acquisitionCostUsd: 5200,
    hostingProvider: 'Demo Host',
    facility: 'Demo Facility A',
    electricityRatePerKwh: 0.045,
    monthlyHostingFeeUsd: 0,
    pool: 'Braiins Pool',
    braiinsWorkerName: 'forge.demo2',
    status: 'active',
    enabled: true,
    warrantyExpiration: '2027-08-15',
    notes: 'Demo asset — not real inventory.',
    createdAt: '2025-08-15T00:00:00.000Z',
    updatedAt: '2025-08-15T00:00:00.000Z',
  },
  {
    id: 'demo-m60s-001',
    model: 'WhatsMiner M60S',
    serialNumber: 'DEMO-M60-001',
    quantity: 1,
    nominalHashrateTh: 186,
    wattage: 3441,
    acquisitionDate: '2025-09-01',
    acquisitionCostUsd: 3800,
    hostingProvider: 'Demo Host',
    facility: 'Demo Facility B',
    electricityRatePerKwh: 0.05,
    monthlyHostingFeeUsd: 75,
    pool: 'Braiins Pool',
    braiinsWorkerName: null,
    status: 'maintenance',
    enabled: false,
    warrantyExpiration: null,
    notes: 'Demo unmapped / disabled asset.',
    createdAt: '2025-09-01T00:00:00.000Z',
    updatedAt: '2025-09-01T00:00:00.000Z',
  },
];

export function createEmptyMinerInput(): import('../domain/types').MinerAssetInput {
  return {
    model: '',
    serialNumber: '',
    quantity: 1,
    nominalHashrateTh: 200,
    wattage: 3500,
    acquisitionDate: null,
    acquisitionCostUsd: null,
    hostingProvider: '',
    facility: '',
    electricityRatePerKwh: null,
    monthlyHostingFeeUsd: null,
    pool: 'Braiins Pool',
    braiinsWorkerName: null,
    status: 'active',
    enabled: true,
    warrantyExpiration: null,
    notes: '',
  };
}
